# # This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# # For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SSR Tests

on:
  push:
    branches: [next]
  pull_request: {}

jobs:
  ssr_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      # Just lint here too. Save some GH Action minutes and not need to use "depends_on" or anything.
      - name: Lint
        run: npm run prettier && npm run lint

      - name: Build
        run: npm run build

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run SSR tests
        # FAIL_FAST to fail on first failing test.
        run: FAIL_FAST="true" SSR_ONLY="true" npm run test

